application: invatar0
version: 1-0
api_version: 1
runtime: python27
threadsafe: true

handlers:

- url: /.*
  script: run.app
  secure: always

skip_files:
# Default settings.
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
# Custom.
- ^venv$
